name: ride_locker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  # UI / State Management
  provider: ^6.1.5+1
  cupertino_icons: ^1.0.8

  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  oktoast: ^3.3.1

 

  # Storage / Utils
  shared_preferences: ^2.5.5

  # 🔥 IMAGE PICKING + FILE PICKING
  image_picker: ^1.1.2
  file_picker: ^10.2.0

  # 🔥 CLOUDINARY SUPPORT (HTTP UPLOAD)
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/onboarding_images/
    - assets/